version: '3.4'

services:
  efcore-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd12345!
    container_name: ef-sql
    ports:
      - "1433:1433"

  dapper-mssql:
    image: rmdataimg
    container_name: dapper-sql
    ports:
      - "1432:1433"
  
  redis-cache:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  rmui:
    image: ${DOCKER_REGISTRY-}rmui
    build:
      context: .
      dockerfile: RMUI/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      DBServer: efcore-mssql
    depends_on:
      - efcore-mssql
      - dapper-mssql
      - redis-cache
    links:
      - "redis-cache"
